= S3 Publish Plugin for Gradle

image:https://github.com/neo4j-contrib/s3-publish-gradle-plugin/workflows/Build/badge.svg[Build status,link=https://github.com/neo4j-contrib/s3-publish-gradle-plugin/actions?query=workflow%3ABuild]
image:https://img.shields.io/maven-metadata/v?metadataUrl=https%3A%2F%2Fplugins.gradle.org%2Fm2%2Fcom.neo4j.gradle.s3.S3Plugin%2Fcom.neo4j.gradle.s3.S3Plugin.gradle.plugin%2Fmaven-metadata.xml[Gradle Plugin,link=https://plugins.gradle.org/plugin/com.neo4j.gradle.s3.S3Plugin]

A plugin to publish files to Amazon S3.

== Usage

[source,gradle]
----
import com.neo4j.gradle.s3.S3UploadTask

plugins {
  id('com.neo4j.gradle.s3.S3UploadTask')
}

s3 {
    profile = 'neo4j'
    region = 'us-east-1'
}


task s3UploadImages(type: S3UploadTask) {
  //overwrite = true
  source = "${projectDir}/images"
  bucket = "dev.assets.neo4j.com"
  destination = "course/${project.name}/images"
  acl.set(CannedAccessControlList.PublicRead)
}
----

The above configuration will publish all images files from the _images_ directory to the bucket _dev.assets.neo4j.com_.
We also configure the destination path and the ACL to apply.

== Publish a new version

The release process is automated and relies on GitHub Actions.
We are using the :robot: `neo4j-oss-build` account to publish on https://plugins.gradle.org.

The `GRADLE_PUBLISH_KEY` and `GRADLE_PUBLISH_SECRET` secrets are configured on GitHub.
See the `.github/workflows/release.yml` file for details.

The release will be performed when a tag is pushed, the procedure is:

. Update the version in the `build.gradle.kts` file and commit
. Tag and push to `master` (don't forget the `v` prefix and replace `x.y.z` with an actual version):
+
 $ git tag vx.y.z && git push origin master --tags

